n = int(input(" enter the num : "))

for i in range(n):
    
    for j in range(i+1):
        print("*", end=" ")
        
    for j in range(n-(i+1)):
        print(" ", end=" ")
        
    for j in range(n-(i+2)):
        print(" ", end=" ")
        
    for j in range(i+1):
        print("*", end=" ")
        
    print()

for i in range(1, n):
    
    for j in range(n-i):
        print("*", end=" ")
        
    for j in range(i):
        print(" ", end=" ")
        
    for j in range(i-1):
        print(" ", end=" ")
        
    for j in range(n-i):
        print("*", end=" ")
        
    print()